export const questions = [
  {
    question: 'Mtoto wa Nyoka ni nani katika nchi yetu?',
    answer:
      'Hii ni Methali mwanangu na inamaanisha kuwa ukiwa mbaya mabaya yatakufwata',
  },
  {
    question: 'Mgeni njoo mwenyeji aponye, hii ni methali au sio?',
    answer:
      'Methali hii inamaana kuwa iwapo mgeni atakuja nyumbani kutakuwa na sherehe na watu watachinja kuku',
  },
  {
    question: 'How do you interject a conversation in Swahili?',
    answer:
      'Kwa Swahili unatumia maneno kama yafwatayo, Tafadhali, samahani, niwie radhi na kadhalika',
  },
];

export const quiz = [
  {
    question: 'Siku njema huonekana ...?',
    choices: {
      "choice1": "asubuhi",
      "choice2": "jioni",
      "choice3": "mchana",
      "choice4": "kesho"
  },
  },
  {
    question: '1Siku njema huonekana ...?',
    choices: {
      "choice1": "asubuhi",
      "choice2": "jioni",
      "choice3": "mchana",
      "choice4": "kesho"
  },
  },
  {
    question: '2Siku njema huonekana ...?',
    choices: {
      "choice1": "asubuhi",
      "choice2": "jioni",
      "choice3": "mchana",
      "choice4": "kesho"
  },
  },
  {
    question: '3Siku njema huonekana ...?',
    choices: {
      "choice1": "asubuhi",
      "choice2": "jioni",
      "choice3": "mchana",
      "choice4": "kesho"
  },
  },
  {
    question: '4Siku njema huonekana ...?',
    choices: {
      "choice1": "asubuhi",
      "choice2": "jioni",
      "choice3": "mchana",
      "choice4": "kesho"
  },
  },
];

export const gameArray1 = [
  'E',
  'L',
  'F',
  'U',
  'B',
  'O',
  'Y',
  'L',
  'U',
  'J',
  'T',
  'E',
  'K',
  'U',
  'S',
  'I',
  'N',
  'I',
  'V',
  'A',
  'N',
  'O',
  'I',
  'I',
  'R',
  'A',
  'B',
  'A',
  'H',
  'M',
  'A',
  'M',
  'C',
  'H',
  'E',
  'K',
  'A',
  'J',
  'A',
  'B',
  'S',
  'K',
  'H',
  'N',
  'D',
  'I',
  'Y',
  'O',
  'O',
  'O',
  'A',
  'O',
  'W',
  'U',
  'N',
  'Y',
  'A',
  'M',
  'A',
  'S',
  'S',
  'N',
  'A',
  'K',
  'U',
  'P',
  'E',
  'N',
  'D',
  'A',
  'A',
  'O',
  'K',
  'A',
  'H',
  'A',
  'W',
  'A',
  'V',
  'X',
];
export const gameObj = {
  elfu: [0, 1, 2, 3],
  leo: [1, 11, 21],
  kahawa: [72, 73, 74, 75, 76, 77],
  moja: [57, 47, 37, 27],
  nakupenda: [61, 62, 63, 64, 65, 66, 67, 68, 69],
  lia: [7, 17, 27],
  nyama: [54, 55, 56, 57, 58],
  mkono: [31, 41, 51, 61, 71],
  kichwa: [12, 22, 32, 42, 52, 62],
  jambo: [9, 19, 29, 39, 49],
  cheka: [32, 33, 34, 35, 36],
  kusini: [12, 13, 14, 15, 16, 17],
  ndiyo: [43, 44, 45, 46, 47],
  asante: [70, 60, 50, 40, 30, 20, 10, 0],
  sasa: [60, 50, 40, 30],
  habari: [28, 27, 26, 25, 24, 23, 22],
};

export const ans = [
  'elfu',
  'leo',
  'kahawa',
  'moja',
  'nakupenda',
  'lia',
  'nyama',
  'mkono',
  'kichwa',
  'jambo',
  'cheka',
  'kusini',
  'ndiyo',
  'asante',
  'sasa',
  'habari',
];
export const colors = [
  'yellow',
  'blue',
  'red',
  'green',
  'black',
  'brown',
  '#2B2D42',
  'teal',
  'silver',
  'purple',
  'gray',
  'orange',
  'maroon',
  'aquamarine',
  'coral',
  'pink',
  'magenta',
];

export const numbers = [
  { number: 0, english: 'zero', swahili: 'sufuri' },
  { number: 1, english: 'one', swahili: 'moja' },
  { number: 2, english: 'two', swahili: 'mbili' },
  { number: 3, english: 'three', swahili: 'tatu' },
  { number: 4, english: 'four', swahili: 'nne' },
  { number: 5, english: 'five', swahili: 'tano' },
  { number: 6, english: 'six', swahili: 'sita' },
  { number: 7, english: 'seven', swahili: 'saba' },
  { number: 8, english: 'eight', swahili: 'nane' },
  { number: 9, english: 'nine', swahili: 'tisa' },
  { number: 10, english: 'ten', swahili: 'kumi' },
  { number: 20, english: 'twenty', swahili: 'ishirini' },
  { number: 30, english: 'thirty', swahili: 'thelathini' },
  { number: 40, english: 'forty', swahili: 'arobaini' },
  { number: 50, english: 'fifty', swahili: 'hamsini' },
  { number: 60, english: 'sixty', swahili: 'sitini' },
  { number: 70, english: 'seventy', swahili: 'sabini' },
  { number: 80, english: 'eighty', swahili: 'themanini' },
  { number: 90, english: 'ninety', swahili: 'tisini' },
  { number: 100, english: '100', swahili: 'mia moja' },
  { number: 1000, english: '1000', swahili: 'elfu moja' },
];
export const directions = [
  { direction: 'east', swahili: 'mashariki' },
  { direction: 'west', swahili: 'magharibi' },
  { direction: 'north', swahili: 'kaskazini' },
  { direction: 'south', swahili: 'kusini' },
  { direction: 'above', swahili: 'juu' },
  { direction: 'below', swahili: 'chini' },
  { direction: 'next to', swahili: 'karibu na' },
  { direction: 'behind', swahili: 'nyuma' },
];
