export const questions = [
  {
    question: 'Mtoto wa Nyoka ni nani katika nchi yetu?',
    answer:
      'Hii ni Methali mwanangu na inamaanisha kuwa ukiwa mbaya mabaya yatakufwata',
  },
  {
    question: 'Mgeni njoo mwenyeji aponye, hii ni methali au sio?',
    answer:
      'Methali hii inamaana kuwa iwapo mgeni atakuja nyumbani kutakuwa na sherehe na watu watachinja kuku',
  },
  {
    question: 'How do you interject a conversation in Swahili?',
    answer:
      'Kwa Swahili unatumia maneno kama yafwatayo, Tafadhali, samahani, niwie radhi na kadhalika',
  },
];

export const quiz = [
  {
    question: 'Siku njema huonekana ...?',
    choices: {
      choice1: 'asubuhi',
      choice2: 'jioni',
      choice3: 'mchana',
      choice4: 'kesho',
    },
  },
  {
    question: '1Siku njema huonekana ...?',
    choices: {
      choice1: 'asubuhi',
      choice2: 'jioni',
      choice3: 'mchana',
      choice4: 'kesho',
    },
  },
  {
    question: '2Siku njema huonekana ...?',
    choices: {
      choice1: 'asubuhi',
      choice2: 'jioni',
      choice3: 'mchana',
      choice4: 'kesho',
    },
  },
  {
    question: '3Siku njema huonekana ...?',
    choices: {
      choice1: 'asubuhi',
      choice2: 'jioni',
      choice3: 'mchana',
      choice4: 'kesho',
    },
  },
  {
    question: '4Siku njema huonekana ...?',
    choices: {
      choice1: 'asubuhi',
      choice2: 'jioni',
      choice3: 'mchana',
      choice4: 'kesho',
    },
  },
];

export const gameArray0 = [
  'E',
  'L',
  'F',
  'U',
  'B',
  'O',
  'Y',
  'L',
  'U',
  'J',
  'T',
  'E',
  'K',
  'U',
  'S',
  'I',
  'N',
  'I',
  'V',
  'A',
  'N',
  'O',
  'I',
  'I',
  'R',
  'A',
  'B',
  'A',
  'H',
  'M',
  'A',
  'M',
  'C',
  'H',
  'E',
  'K',
  'A',
  'J',
  'A',
  'B',
  'S',
  'K',
  'H',
  'N',
  'D',
  'I',
  'Y',
  'O',
  'O',
  'O',
  'A',
  'O',
  'W',
  'U',
  'N',
  'Y',
  'A',
  'M',
  'A',
  'S',
  'S',
  'N',
  'A',
  'K',
  'U',
  'P',
  'E',
  'N',
  'D',
  'A',
  'A',
  'O',
  'K',
  'A',
  'H',
  'A',
  'W',
  'A',
  'V',
  'X',
];
export const gameArray1 = [
  'A',
  'S',
  'I',
  'T',
  'A',
  'T',
  'U',
  'X',
  'Y',
  'Z',
  'M',
  'A',
  'H',
  'A',
  'R',
  'A',
  'G',
  'W',
  'E',
  'S',
  'C',
  'B',
  'A',
  'B',
  'Q',
  'N',
  'U',
  'T',
  'N',
  'A',
  'H',
  'A',
  'I',
  'M',
  'A',
  'O',
  'U',
  'A',
  'Y',
  'M',
  'E',
  'N',
  'L',
  'I',
  'A',
  'Y',
  'A',
  'M',
  'U',
  'A',
  'L',
  'O',
  'B',
  'J',
  'U',
  'U',
  'Q',
  'B',
  'M',
  'K',
  'E',
  'K',
  'W',
  'A',
  'H',
  'E',
  'R',
  'I',
  'A',
  'I',
  'L',
  'A',
  'K',
  'A',
  'N',
  'D',
  'O',
  'R',
  'S',
  'T',
];
export const gameArray2 = [
  'N',
  'A',
  'K',
  'U',
  'P',
  'E',
  'N',
  'D',
  'A',
  'B',
  'U',
  'A',
  'W',
  'E',
  'K',
  'U',
  'M',
  'I',
  'G',
  'A',
  'S',
  'H',
  'A',
  'P',
  'A',
  'N',
  'A',
  'S',
  'O',
  'K',
  'I',
  'C',
  'H',
  'I',
  'N',
  'I',
  'U',
  'A',
  'B',
  'U',
  'L',
  'Z',
  'E',
  'X',
  'N',
  'W',
  'A',
  'I',
  'M',
  'N',
  'I',
  'B',
  'R',
  'Y',
  'E',
  'W',
  'S',
  'D',
  'S',
  'Y',
  'E',
  'S',
  'I',
  'T',
  'I',
  'N',
  'I',
  'I',
  'T',
  'W',
  'D',
  'C',
  'N',
  'A',
  'K',
  'U',
  'T',
  'A',
  'K',
  'A',
];
export const gameObj0 = {
  elfu: [0, 1, 2, 3],
  leo: [1, 11, 21],
  kahawa: [72, 73, 74, 75, 76, 77],
  moja: [57, 47, 37, 27],
  nakupenda: [61, 62, 63, 64, 65, 66, 67, 68, 69],
  lia: [7, 17, 27],
  nyama: [54, 55, 56, 57, 58],
  mkono: [31, 41, 51, 61, 71],
  kichwa: [12, 22, 32, 42, 52, 62],
  jambo: [9, 19, 29, 39, 49],
  cheka: [32, 33, 34, 35, 36],
  kusini: [12, 13, 14, 15, 16, 17],
  ndiyo: [43, 44, 45, 46, 47],
  asante: [70, 60, 50, 40, 30, 20, 10, 0],
  sasa: [60, 50, 40, 30],
  habari: [28, 27, 26, 25, 24, 23, 22],
};

export const gameObj1 = {
  mchele: [10, 20, 30, 40, 50, 60],
  sita: [1, 2, 3, 4],
  maharagwe: [10, 11, 12, 13, 14, 15, 16, 17, 18],
  tano: [5, 15, 25, 35],
  saba: [1, 11, 21, 31],
  kwaheri: [61, 62, 63, 64, 65, 66, 66, 67],
  juu: [53, 54, 55],
  lia: [42, 43, 44],
  samaki: [19, 29, 39, 49, 59, 69],
  kando: [72, 73, 74, 75, 76],
  nyuma: [28, 38, 48, 58, 68],
  imba: [43, 33, 23, 13],
  mayai: [47, 46, 45, 44, 43],
  tambi: [67, 57, 47, 37, 27],
  tatu: [3, 4, 5, 6],
};
export const gameObj2 = {
  nakupenda: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  usilie: [10, 20, 30, 40, 50, 60],
  hapana: [1, 2, 3, 4, 5, 6],
  kumi: [14, 15, 16, 17],
  saidia: [27, 37, 47, 57, 67, 77],
  nakutaka: [72, 73, 74, 75, 76, 77, 78, 79],
  sitini: [61, 62, 63, 64, 65, 66],
  nne: [34, 44, 54],
  kunywa: [29, 39, 49, 59, 69, 79],
  kwaheri: [2, 12, 22, 32, 42, 52, 62],
  mboga: [48, 38, 28, 18, 8],
  chini: [31, 32, 33, 34, 35],
  tisa: [76, 66, 56, 46],
};
export const gameArrayList = [gameArray0, gameArray1, gameArray2];
export const gameObjList = [gameObj0, gameObj1, gameObj2];
export const ans0 = [
  'elfu',
  'leo',
  'kahawa',
  'moja',
  'nakupenda',
  'lia',
  'nyama',
  'mkono',
  'kichwa',
  'jambo',
  'cheka',
  'kusini',
  'ndiyo',
  'asante',
  'sasa',
  'habari',
];
export const ans1 = [
  'mchele',
  'sita',
  'maharagwe',
  'tano',
  'saba',
  'kwaheri',
  'juu',
  'lia',
  'samaki',
  'kando',
  'nyuma',
  'imba',
  'mayai',
  'tambi',
  'tatu',
];
export const ans2 = [
  'nakupenda',
  'usilie',
  'hapana',
  'kumi',
  'saidia',
  'nakutaka',
  'sitini',
  'nne',
  'kunywa',
  'kwaheri',
  'mboga',
  'chini',
  'tisa',
];
export const ansList = [ans0, ans1, ans2]
export const colors = [
  'yellow',
  'blue',
  'red',
  'green',
  'black',
  'brown',
  '#2B2D42',
  'teal',
  'silver',
  'purple',
  'gray',
  'orange',
  'maroon',
  'aquamarine',
  'coral',
  'pink',
  'magenta',
];

export const numbers = [
  { number: 0, english: 'zero', swahili: 'sufuri' },
  { number: 1, english: 'one', swahili: 'moja' },
  { number: 2, english: 'two', swahili: 'mbili' },
  { number: 3, english: 'three', swahili: 'tatu' },
  { number: 4, english: 'four', swahili: 'nne' },
  { number: 5, english: 'five', swahili: 'tano' },
  { number: 6, english: 'six', swahili: 'sita' },
  { number: 7, english: 'seven', swahili: 'saba' },
  { number: 8, english: 'eight', swahili: 'nane' },
  { number: 9, english: 'nine', swahili: 'tisa' },
  { number: 10, english: 'ten', swahili: 'kumi' },
  { number: 20, english: 'twenty', swahili: 'ishirini' },
  { number: 30, english: 'thirty', swahili: 'thelathini' },
  { number: 40, english: 'forty', swahili: 'arobaini' },
  { number: 50, english: 'fifty', swahili: 'hamsini' },
  { number: 60, english: 'sixty', swahili: 'sitini' },
  { number: 70, english: 'seventy', swahili: 'sabini' },
  { number: 80, english: 'eighty', swahili: 'themanini' },
  { number: 90, english: 'ninety', swahili: 'tisini' },
  { number: 100, english: '100', swahili: 'mia moja' },
  { number: 1000, english: '1000', swahili: 'elfu moja' },
];
export const directions = [
  { direction: 'east', swahili: 'mashariki' },
  { direction: 'west', swahili: 'magharibi' },
  { direction: 'north', swahili: 'kaskazini' },
  { direction: 'south', swahili: 'kusini' },
  { direction: 'above', swahili: 'juu' },
  { direction: 'below', swahili: 'chini' },
  { direction: 'next to', swahili: 'karibu na' },
  { direction: 'behind', swahili: 'nyuma' },
];
